version: '3'


volumes:
  fastapi_data:

services:
  api:
    container_name: fastapi
    build:
            context: ./api
            dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - path: ./.env
        required: true
      - path: ./.env.local
        required: false

    volumes:
      - fastapi_data:./api

  fe:
    container_name: reactapp
    build:
            context: ./fe
            dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - path: ./.env
        required: true
      - path: ./.env.local
        required: false
    depends_on:
      - api

