version: '3'


volumes:
  fastapi_data:

services:
  api:
    container_name: fastapi
    build:
            context: ./
            dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - path: ./.env
        required: true
      - path: ./.env.local
        required: false

    volumes:
      - fastapi_data:/


